const ProblemActionTypes = {
  FETCH_PROBLEMS_START: "FETCH_PROBLEMS_START",
  FETCH_PROBLEMS_SUCCESS: "FETCH_PROBLEMS_SUCCESS",
  FETCH_PROBLEMS_FAILURE: "FETCH_PROBLEMS_SUCCESS",
};

export default ProblemActionTypes;
