const PROBLEMS_DATA = [
  {
    title: "array",
    problems: [
      {
        id: 1,
        title: "Add Two numbers",
        description: "Program Describing how to add two numbers in cpp",
        language: "CPP",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        inputs: "a = 10, b = 20",
        outputs: "30",
        sourceCode: "asdfjkfhlksadjflksadjflkds",
      },
      {
        id: 2,
        title: "Maximize the Profits",
        description: "Program Describing how to add two numbers in cpp",
        language: "CPP",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        inputs: "a = 10, b = 20",
        outputs: "30",
        sourceCode: "asdfjkfhlksadjflksadjflkds",
      },
      {
        id: 3,
        title: "Minimize the Costs",
        description: "Program Describing how to add two numbers in cpp",
        language: "CPP",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        inputs: "a = 10, b = 20",
        outputs: "30",
        sourceCode: "asdfjkfhlksadjflksadjflkds",
      },
    ],
  },
  {
    title: "linked-list",
    problems: [
      {
        id: 4,
        title: "Add Two numbers",
        description: "Program Describing how to add two numbers in cpp",
        language: "CPP",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        inputs: "a = 10, b = 20",
        outputs: "30",
        sourceCode: "asdfjkfhlksadjflksadjflkds",
      },
      {
        id: 5,
        title: "Maximize the Profits",
        description: "Program Describing how to add two numbers in cpp",
        language: "CPP",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        inputs: "a = 10, b = 20",
        outputs: "30",
        sourceCode: "asdfjkfhlksadjflksadjflkds",
      },
      {
        id: 6,
        title: "Minimize the Costs",
        description: "Program Describing how to add two numbers in cpp",
        language: "CPP",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        inputs: "a = 10, b = 20",
        outputs: "30",
        sourceCode: "asdfjkfhlksadjflksadjflkds",
      },
    ],
  },
  {
    title: "stack",
    problems: [
      {
        id: 1,
        title: "Add Two numbers",
        description: "Program Describing how to add two numbers in cpp",
        language: "CPP",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        inputs: "a = 10, b = 20",
        outputs: "30",
        sourceCode: "asdfjkfhlksadjflksadjflkds",
      },
      {
        id: 2,
        title: "Maximize the Profits",
        description: "Program Describing how to add two numbers in cpp",
        language: "CPP",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        inputs: "a = 10, b = 20",
        outputs: "30",
        sourceCode: "asdfjkfhlksadjflksadjflkds",
      },
      {
        id: 3,
        title: "Minimize the Costs",
        description: "Program Describing how to add two numbers in cpp",
        language: "CPP",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        inputs: "a = 10, b = 20",
        outputs: "30",
        sourceCode: "asdfjkfhlksadjflksadjflkds",
      },
    ],
  },

  {
    title: "queue",
    problems: [
      {
        id: 1,
        title: "Add Two numbers",
        description: "Program Describing how to add two numbers in cpp",
        language: "CPP",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        inputs: "a = 10, b = 20",
        outputs: "30",
        sourceCode: "asdfjkfhlksadjflksadjflkds",
      },
      {
        id: 2,
        title: "Maximize the Profits",
        description: "Program Describing how to add two numbers in cpp",
        language: "CPP",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        inputs: "a = 10, b = 20",
        outputs: "30",
        sourceCode: "asdfjkfhlksadjflksadjflkds",
      },
      {
        id: 3,
        title: "Minimize the Costs",
        description: "Program Describing how to add two numbers in cpp",
        language: "CPP",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        inputs: "a = 10, b = 20",
        outputs: "30",
        sourceCode: "asdfjkfhlksadjflksadjflkds",
      },
    ],
  },

  {
    title: "tree",
    problems: [
      {
        id: 1,
        title: "Add Two numbers",
        description: "Program Describing how to add two numbers in cpp",
        language: "CPP",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        inputs: "a = 10, b = 20",
        outputs: "30",
        sourceCode: "asdfjkfhlksadjflksadjflkds",
      },
      {
        id: 2,
        title: "Maximize the Profits",
        description: "Program Describing how to add two numbers in cpp",
        language: "CPP",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        inputs: "a = 10, b = 20",
        outputs: "30",
        sourceCode: "asdfjkfhlksadjflksadjflkds",
      },
      {
        id: 3,
        title: "Minimize the Costs",
        description: "Program Describing how to add two numbers in cpp",
        language: "CPP",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        inputs: "a = 10, b = 20",
        outputs: "30",
        sourceCode: "asdfjkfhlksadjflksadjflkds",
      },
    ],
  },

  {
    title: "graph",
    problems: [
      {
        id: 1,
        title: "Add Two numbers",
        description: "Program Describing how to add two numbers in cpp",
        language: "CPP",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        inputs: "a = 10, b = 20",
        outputs: "30",
        sourceCode: "asdfjkfhlksadjflksadjflkds",
      },
      {
        id: 2,
        title: "Maximize the Profits",
        description: "Program Describing how to add two numbers in cpp",
        language: "CPP",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        inputs: "a = 10, b = 20",
        outputs: "30",
        sourceCode: "asdfjkfhlksadjflksadjflkds",
      },
      {
        id: 3,
        title: "Minimize the Costs",
        description: "Program Describing how to add two numbers in cpp",
        language: "CPP",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        inputs: "a = 10, b = 20",
        outputs: "30",
        sourceCode: "asdfjkfhlksadjflksadjflkds",
      },
    ],
  },

  {
    title: "divide-and-conquer",
    problems: [
      {
        id: 1,
        title: "Add Two numbers",
        description: "Program Describing how to add two numbers in cpp",
        language: "CPP",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        inputs: "a = 10, b = 20",
        outputs: "30",
        sourceCode: "asdfjkfhlksadjflksadjflkds",
      },
      {
        id: 2,
        title: "Maximize the Profits",
        description: "Program Describing how to add two numbers in cpp",
        language: "CPP",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        inputs: "a = 10, b = 20",
        outputs: "30",
        sourceCode: "asdfjkfhlksadjflksadjflkds",
      },
      {
        id: 3,
        title: "Minimize the Costs",
        description: "Program Describing how to add two numbers in cpp",
        language: "CPP",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        inputs: "a = 10, b = 20",
        outputs: "30",
        sourceCode: "asdfjkfhlksadjflksadjflkds",
      },
    ],
  },

  {
    title: "backtracking",
    problems: [
      {
        id: 1,
        title: "Add Two numbers",
        description: "Program Describing how to add two numbers in cpp",
        language: "CPP",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        inputs: "a = 10, b = 20",
        outputs: "30",
        sourceCode: "asdfjkfhlksadjflksadjflkds",
      },
      {
        id: 2,
        title: "Maximize the Profits",
        description: "Program Describing how to add two numbers in cpp",
        language: "CPP",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        inputs: "a = 10, b = 20",
        outputs: "30",
        sourceCode: "asdfjkfhlksadjflksadjflkds",
      },
      {
        id: 3,
        title: "Minimize the Costs",
        description: "Program Describing how to add two numbers in cpp",
        language: "CPP",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        inputs: "a = 10, b = 20",
        outputs: "30",
        sourceCode: "asdfjkfhlksadjflksadjflkds",
      },
    ],
  },

  {
    title: "greedy-algorithms",
    problems: [
      {
        id: 1,
        title: "Add Two numbers",
        description: "Program Describing how to add two numbers in cpp",
        language: "CPP",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        inputs: "a = 10, b = 20",
        outputs: "30",
        sourceCode: "asdfjkfhlksadjflksadjflkds",
      },
      {
        id: 2,
        title: "Maximize the Profits",
        description: "Program Describing how to add two numbers in cpp",
        language: "CPP",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        inputs: "a = 10, b = 20",
        outputs: "30",
        sourceCode: "asdfjkfhlksadjflksadjflkds",
      },
      {
        id: 3,
        title: "Minimize the Costs",
        description: "Program Describing how to add two numbers in cpp",
        language: "CPP",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        inputs: "a = 10, b = 20",
        outputs: "30",
        sourceCode: "asdfjkfhlksadjflksadjflkds",
      },
    ],
  },

  {
    title: "dynamic-programming",
    problems: [
      {
        id: 1,
        title: "Add Two numbers",
        description: "Program Describing how to add two numbers in cpp",
        language: "CPP",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        inputs: "a = 10, b = 20",
        outputs: "30",
        sourceCode: "asdfjkfhlksadjflksadjflkds",
      },
      {
        id: 2,
        title: "Maximize the Profits",
        description: "Program Describing how to add two numbers in cpp",
        language: "CPP",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        inputs: "a = 10, b = 20",
        outputs: "30",
        sourceCode: "asdfjkfhlksadjflksadjflkds",
      },
      {
        id: 3,
        title: "Minimize the Costs",
        description: "Program Describing how to add two numbers in cpp",
        language: "CPP",
        timeComplexity: "O(n)",
        spaceComplexity: "O(1)",
        inputs: "a = 10, b = 20",
        outputs: "30",
        sourceCode: "asdfjkfhlksadjflksadjflkds",
      },
    ],
  },
];

export default PROBLEMS_DATA;
